COMMON_SELECTORS = {
    "name": [
        "h1.product_title",
        "[class*='product-title']",
        "[class*='product_name']",
        "h1",
        "h2",
        "[class*='product'][class*='name']",
        "[id*='title']",
    ],
    "price": [
        ".current-sale-price",
        ".fds__core-web-purchase-price",
        ".price-current",
        ".price-now",
        ".sale-price",
        ".special-price",
        ".offer-price",
        ".product-price",
        ".price .woocommerce-Price-amount",
        ".price bdi",
        "p.price ins .woocommerce-Price-amount",
        "p.price del .woocommerce-Price-amount",
        "span.price",
        "span[class*='price']",
        "[class*='price']",
        "[class*='cost']",
        "[class*='amount']",
        "[id*='price']",
        "[data-price]",
    ],
    "brand": [
        "[class*='brand']",
        "[id*='brand']",
        "meta[itemprop='brand']",
        "div.brand",
        ".product-brand",
        ".brand-name",
    ],
    "fibre_count": [
        "[class*='fabric']",
        "[class*='material']",
        "[class*='composition']",
        "[class*='fibre']",
        "[class*='fiber']",
        "li",
        "span",
        "[class*='content']",
        "[class*='spec']",
    ],
}
